### ISSUE TITLE
[Doc] Tutorial

### ISSUE THREAD

**Issue by huangyz0918** [cap-ntu/ML-Model-CI#77]
### Roadmap 

- [x] Register Model in the Model Database
- [x] Converting Model to Different Frameworks
- [x] Profiling Model Automatically
- [x] Retrieve and Deploy Model to Specific Device
